[[purgecss]]
css = "global.css"
content = ["templates/front_office.html", "templates/blog.html"]

[[purgecss]]
css = "pages/article.css"
content = ["templates/pages/blog/article.html"]

[[purgecss]]
css = "pages/blog.css"
content = ["templates/pages/blog/category.html", "templates/pages/blog/index.html"]

[[purgecss]]
css = "pages/contact.css"
content = ["templates/pages/contact.html"]

[[purgecss]]
css = "pages/index.css"
content = ["templates/pages/index.html"]

[[purgecss]]
css = "pages/legals.css"
content = ["templates/pages/legals.html"]

[[purgecss]]
css = "pages/motion_design.css"
content = ["templates/pages/motion_design.html"]

[[purgecss]]
css = "pages/my_little_plus.css"
content = ["templates/pages/my_little_plus.html"]

[[purgecss]]
css = "pages/portfolio.css"
content = ["templates/pages/portfolio.html", "templates/pages/portfolio_project.html"]

[[purgecss]]
css = "pages/project.css"
content = ["templates/pages/portfolio_project.html"]

# BackOffice
[[purgecss]]
css = "admin.css"
content = ["templates/back_office.html"]

[[purgecss]]
css = "pages/admin/blog.css"
content = ["templates/pages/admin/blog.html"]

[[purgecss]]
css = "pages/admin/home.css"
content = ["templates/pages/admin/home.html"]

[[purgecss]]
css = "pages/admin/login.css"
content = ["templates/pages/admin/login.html"]

[[purgecss]]
css = "pages/admin/my_little_plus.css"
content = ["templates/pages/admin/my_little_plus.html"]

[[purgecss]]
css = "pages/admin/my_little_plus.css"
content = ["templates/pages/admin/my_little_plus.html"]

[[purgecss]]
css = "pages/admin/portfolio.css"
content = ["templates/pages/admin/portfolio.html"]

[[purgecss]]
css = "pages/admin/settings.css"
content = ["templates/pages/admin/settings.html"]